version: "3.9"

services:

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    volumes:
    - fileuploadservice_dremio-data:/var/lib/dremio

  minioserver:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    container_name: minioserver
    command: server /data --console-address :9001
    volumes:
      - data-lakehouse_minio-data:/data
      - data-lakehouse_minio-config:/root/.minio

  spark_notebook:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
    env_file: .env
    container_name: notebook
    volumes:
      - ./notebooks:/home/jovyan/work

  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - 19120:19120

  streamlit-app:
    image: streamlit-app
    build:
      context: ./app
    ports:
      - 80:8501
    volumes:
      - ./app:/app
    container_name: streamlit-app
    restart: always

  flask-api:
    image: flask-api
    build:
      context: ./flask
    ports:
      - 5000:5000
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=development
    container_name: flask-api
    restart: always

volumes:
  data-lakehouse_minio-data:
    external: true
  data-lakehouse_minio-config:
    external: true
  fileuploadservice_dremio-data:
    external: true

networks:
  default:
    name: iceberg_env
    driver: bridge

